// Static mock data for Barbershop Booking Platform

import { Barbershop, Service, Barber } from '@/types';

export const mockServices: Service[] = [
  {
    id: 's1',
    name: 'Soch olish',
    description: 'Professional soch olish xizmati',
    duration: 30,
    price: 50000,
    category: 'haircut',
  },
  {
    id: 's2',
    name: 'Soqol tuzatish',
    description: 'Soqol tuzatish va stilizatsiya',
    duration: 20,
    price: 30000,
    category: 'beard',
  },
  {
    id: 's3',
    name: 'Soch + Soqol',
    description: 'To\'liq xizmat - soch va soqol',
    duration: 45,
    price: 70000,
    category: 'haircut-beard',
  },
  {
    id: 's4',
    name: 'Soch bo\'yash',
    description: 'Professional soch bo\'yash xizmati',
    duration: 90,
    price: 150000,
    category: 'coloring',
  },
  {
    id: 's5',
    name: 'Soch stilizatsiyasi',
    description: 'Soch stilizatsiyasi va parvarish',
    duration: 60,
    price: 80000,
    category: 'styling',
  },
];

export const mockBarbers: Barber[] = [
  {
    id: 'b1',
    name: 'Akmal Karimov',
    specialization: 'Classic & Modern',
    experience: 5,
    rating: 4.8,
    services: ['s1', 's2', 's3'],
  },
  {
    id: 'b2',
    name: 'Javohir Toshmatov',
    specialization: 'Fade & Undercut',
    experience: 7,
    rating: 4.9,
    services: ['s1', 's3', 's5'],
  },
  {
    id: 'b3',
    name: 'Sardor Aliyev',
    specialization: 'Beard Specialist',
    experience: 4,
    rating: 4.7,
    services: ['s2', 's3'],
  },
  {
    id: 'b4',
    name: 'Dilshod Rahimov',
    specialization: 'Coloring Expert',
    experience: 6,
    rating: 4.9,
    services: ['s4', 's5'],
  },
];

export const mockBarbershops: Barbershop[] = [
  {
    id: 'bs1',
    name: 'Premium Barbershop',
    description: 'Premium barbershop with experienced barbers and modern equipment. We provide high-quality services in a comfortable atmosphere.',
    address: 'Amir Temur ko\'chasi, 15',
    city: 'Tashkent',
    district: 'Yunusabad',
    phone: '+998901234567',
    email: 'premium@barbershop.uz',
    image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80'
    ],
    workingHours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    services: mockServices,
    barbers: [mockBarbers[0], mockBarbers[1]],
    amenities: ['Wi-Fi', 'Parking', 'Air Conditioning', 'Coffee'],
  },
  {
    id: 'bs2',
    name: 'Classic Cuts',
    description: 'Traditional barbershop with classic style. Perfect for those who appreciate timeless elegance.',
    address: 'Navoiy ko\'chasi, 42',
    city: 'Tashkent',
    district: 'Mirobod',
    phone: '+998901234568',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80',
    workingHours: {
      monday: { open: '08:00', close: '19:00' },
      tuesday: { open: '08:00', close: '19:00' },
      wednesday: { open: '08:00', close: '19:00' },
      thursday: { open: '08:00', close: '19:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '00:00', close: '00:00', closed: true },
    },
    services: mockServices.slice(0, 3),
    barbers: [mockBarbers[2]],
    amenities: ['Wi-Fi', 'Parking'],
  },
  {
    id: 'bs3',
    name: 'Modern Style Barbershop',
    description: 'Modern barbershop with latest trends and techniques. Young and energetic atmosphere.',
    address: 'Bunyodkor ko\'chasi, 78',
    city: 'Tashkent',
    district: 'Chilonzor',
    phone: '+998901234569',
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
    workingHours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    services: mockServices,
    barbers: mockBarbers,
    amenities: ['Wi-Fi', 'Parking', 'Air Conditioning', 'Coffee', 'TV'],
  },
  {
    id: 'bs4',
    name: 'Elite Barbershop',
    description: 'Luxury barbershop experience with premium services and VIP treatment.',
    address: 'Mustaqillik maydoni, 5',
    city: 'Tashkent',
    district: 'Shaykhontohur',
    phone: '+998901234570',
    image: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80',
    workingHours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '19:00' },
    },
    services: mockServices,
    barbers: [mockBarbers[0], mockBarbers[3]],
    amenities: ['Wi-Fi', 'Parking', 'Air Conditioning', 'Coffee', 'Massage Chair'],
  },
];

export const cities = ['Tashkent', 'Samarkand', 'Bukhara', 'Andijan', 'Namangan', 'Fergana'];
export const districts = ['Yunusabad', 'Mirobod', 'Chilonzor', 'Shaykhontohur', 'Olmazor', 'Uchtepa'];
